### ISSUE TITLE
Issues running/compiling examples on mac

### ISSUE THREAD

**Issue by mgustavsson** [vkngwrapper/core#1]
Very excited to see this library for Go - but I had some issues to get the examples to work on my Intel mac:

The https://github.com/vkngwrapper/examples/tree/main/vulkan_tutorial/sdl2 example compiled, but did not run at first for me:

> 2022/08/09 04:10:55 [Error General] - vkCreateInstance: Found drivers that contain devices which support the portability subset, but the portability enumeration bit was not set!. Applications that wish to enumerate portability drivers must set the VK_INSTANCE_CREATE_ENUMERATE_PORTABILITY_BIT_KHR bit in the VkInstanceCreateInfo flags andenable the VK_KHR_portability_enumeration instance extension.
> 2022/08/09 04:10:55 [Error General] - vkCreateInstance: Found no drivers!
> 2022/08/09 04:10:55 vulkan error: incompatible driver

I added this line in the createInstance() function:

`instanceOptions.EnabledExtensionNames = append(instanceOptions.EnabledExtensionNames, "VK_KHR_portability_enumeration")`

And also set "Flags" to 1 in the same function:

```
instanceOptions := core1_0.InstanceCreateInfo{
		ApplicationName:    "Hello Triangle",
		ApplicationVersion: common.CreateVersion(1, 0, 0),
 		EngineName:         "No Engine",
 		EngineVersion:      common.CreateVersion(1, 0, 0),
 		APIVersion:         common.Vulkan1_2,
 		Flags:              1,
 }
```

And then it ran without issues  🥳:
<img width="816" alt="image" src="https://user-images.githubusercontent.com/93975132/183551234-c1b62ac6-a636-490d-9062-448f17fb5b19.png">

Then I tried the https://github.com/vkngwrapper/vulkan-tutorial/tree/main/steps/01_instance_creation example but that failed to build with a link error:

```
go run ./steps/01_instance_creation/
# github.com/vkngwrapper/vulkan-tutorial/steps/01_instance_creation
/Users/slvmnd/gosrc/pkg/tool/darwin_amd64/link: running clang failed: exit status 1
Undefined symbols for architecture x86_64:
  "_vkGetInstanceProcAddr", referenced from:
      _github.com/vkngwrapper/core._Cfpvar_fp_vkGetInstanceProcAddr in go.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Let me know if there is some other information that would be helpful.

**Comment by CannibalVox** [comment]
The bit about portability enumeration is interesting- it seems like mac should have never worked for me, but it did so I need to investigate that a little more thoroughly. I will get that functionality working, though.

The latter bit is a little more oddball- It's clear to me that step 29 is working because it loads its vulkan from SDL2 and step 1 is not working because it needs to link to static vulkan libs because vulkan is loading from your local system in that step. I really believe that the Vulkan SDK should have installed static libs/includes/etc. And you must have the SDK or step 29 couldn't have run successfully. I wonder if the mac setup is unusual for the SDK.

**Comment by CannibalVox** [comment]
The tutorial should build properly again starting with step 3, though.

**Comment by CannibalVox** [comment]
After a teensy bit of pre-bed investigation, khr_portability_enumeration was released a year after khr_portability_subset, and the big red warning on khr_portability_subset is it's provisional and still subject to change. I suspect there was a period of time when having khr_portability_subset enabled was sufficient to enumerate nonconformant devices, and my mac has a version of the vulkan SDK or perhaps a version of vkmolten from that period of time. Will test this theory tomorrow.

**Comment by mgustavsson** [comment]
You are right, steps 03 and onwards builds for me but fails to run due to the khr_portability_enumeration setup, which should be fixable in the same way as above 👍

The link error on step 01 and 02 is not a problem for me then, but in case it is useful here is some more info from my machine:
clang -x c -v -E /dev/null says:
> #include "..." search starts here:
> #include <...> search starts here:
>  /usr/local/include
>  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.0.0/include
>  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include
>  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include 
> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks (framework directory) 

And clang -Xlinker -v gives:
> configured to support archs: armv6 armv7 armv7s arm64 arm64e arm64_32 i386 x86_64 x86_64h armv6m armv7k armv7m armv7em
> Library search paths:
> 	/usr/local/lib
> 	/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib
> Framework search paths:
> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/

Vulkan headers are present in /usr/local/include/vulkan and /usr/local/lib contains libvulkan.dylib but no vulkan related .a files.

There are .a files in the VulkanSDK directory in my user home directory, for example:
/Users/slvmnd/VulkanSDK/1.3.216.0/MoltenVK/MoltenVK.xcframework/macos-arm64_x86_64/libMoltenVK.a

But these .a files or the MoltenVK.xcframework has not been copied by the VulkanSDK installer to any system directories.

These pages might be of interest regarding this:
https://github.com/KhronosGroup/MoltenVK/issues/1122
https://github.com/KhronosGroup/MoltenVK/blob/master/Docs/MoltenVK_Runtime_UserGuide.md#install

Not sure how feasible it is, but I think most Go developers would actually prefer if vkngwrapper or an accompanying helper package bundled the vulkan libraries for different OS:es and header files in a go-gettable package. If I make a library, game or GUI app using vkngwrapper, it is much easier for me to get other developers to try it out and collaborate on like that. 

For example gettings started with https://github.com/fyne-io/fyne or https://github.com/hajimehoshi/ebiten is usually just a matter of issuing one "go get/install/run" command.

**Comment by mgustavsson** [comment]
Sounds good, thanks for the help and making this library - I'm looking forward to trying it out some more!

**Comment by CannibalVox** [comment]
Hello again!

1. khr_portability_enumeration has been incorporated into all vulkan-tutorial steps and the vulkan-tutorial example in the examples repo
2. The build issue when linking to the system vulkan proc on mac has been fixed. I was linking to the libs in the Vulkan SDK incorrectly, and I have fixed that problem. It should now Just Work for any user that has the Vulkan SDK installed. The Vulkan SDK needs to remain a prereq for vkngwrapper for a lot of reasons (for one, it installs vkmolten and the validation layer) so I think this is a good way to leave things. The main issue with mac IMO is how to package for final release, but at this time that's a feature request more than a bug.

The only remaining item here is that the LunarG examples in the examples repo still have the khr_portability_enumeration issue so I will leave this task open until that is fixed.

In the meantime, can you verify that you are no longer experiencing the issues you identified?

**Comment by mgustavsson** [comment]
Hi,

Yes now the tutorial steps all work for me, both the link error on 01/02 and the portability issues are fixed 👍

Requiring the SDK for developers is perhaps the best way forward, but of course as you say there needs to be a way to build a binary for end users that works without the SDK installed.

Thanks!

**Comment by mgustavsson** [comment]
Forgot to mention, i needed to run "go mod tidy" to get them to build though:
```
go run ./01_instance_creation/
01_instance_creation/main.go:9:2: golang.org/x/sys@v0.0.0-20220808155132-1c4a2a72c664: missing go.sum entry; to add it:
	go mod download golang.org/x/sys
```

**Comment by CannibalVox** [comment]
LunarG examples now all work with mac. Additionally I checked in the go mod tidy for vulkan-tutorial.  As a result, I think this is good to close.
