### ISSUE TITLE
CmdBindVertexBuffers doesn't support setting firstBinding

### ISSUE THREAD

**Issue by mgustavsson** [vkngwrapper/core#3]
As far as I can see the firstBinding field in CommandBuffer.CmdBindVertexBuffers doesn't seem to be settable? 

Not sure how often people do it - but I was looking for it in order to keep one buffer bound during several draw calls and change the second buffer binding only between draw calls - I can of course re-bind both buffers, but it would be nice to be able to specify just the one binding needing to be changed.

**Comment by CannibalVox** [comment]
Wow, what a goof! I will introduce a breaking change to fix this, I'm not sure how I managed to mess that up.

**Comment by CannibalVox** [comment]
I've pushed a new version of all vkngwrapper repos that uses the correct signature with the missing parameter. Please let me know if this addresses the issue for you.

**Comment by mgustavsson** [comment]
Yes, looks good - thanks!
